# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Connor Leech
subtitle: "This is the subtitle"
blurb: "This is the blurb" 
description: "This is the description"
author: Connor Leech
language:
timezone:

# Social
social:
  github: https://github.com/connor11528
  twitter: https://twitter.com/connor11528
  facebook: 
  rss: atom.xml
  linkedin: https://linkedin.com/in/connorleech
  stackoverflow: https://stackoverflow.com/users/2031033/connor-leech

# Miscellaneous
color_scheme: blue  # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "" # as a string, from https://twitter.com/settings/widgets
twitter_username: connor11528 # twitter username without the @
default_author: Connor Leech

# Header Menu
# menu:
#   Home: /
#   Projects: /projects/
#   Blog: /archives/ # can set archive-dir in root config to custom value
#   Contact: /contact/
#   About: /about/

# Featured Note
feature_note_title: 'Build a Task List with Laravel 5 and Vue 2'
feature_note_date: 'July 17th, 2017'
feature_note_author: 'Connor Leech'
feature_note_path: "blog/Build-a-Task-List-with-Laravel-5-and-Vue-2/"
feature_note_excerpt: 'This tutorial goes through creating a Task List application with Laravel 5 and Vue 2. 
After going through this tutorial you will have the source code for creating a Tasks dynamically with client side Javascript
and persisting them to MySQL with PHP.'

# Featured Case Study
# feature_case_title: 'Verdes Pinpoints'
# feature_case_date: 'June 14th, 2016'
# feature_case_author: 'Patrick Steadman'
# feature_case_path: 'blog/'
# feature_case_project_path: 'http://pinpoints.io'
# feature_case_lede: 'We built an interactive 3D landing page for a marketing data visualization tool.'
# feature_case_excerpt: 'The engineers who built ReactJS were inspired by the efficiency 
# and simplicity of the “DOOM” video game engine, 
# so it’s not surprising that React is a good tool for building responsive 3D websites. 
# The PinPoints build convinced us that React’s declarative components are a great fit 
# for developing 3D user interfaces in the browser.'
   

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://connorleech.info
root: /
permalink: blog/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: blog
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

marked:
  breaks: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: computer-lab

# SASS
node_sass:
    outputStyle: nested
    precision: 5
    sourceComments: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/connor11528/connor11528.github.io.git # git@github.com:connor11528/connor11528.github.io.git
  branch: master
  message: auto deploy!
